{{- if .Values.keda.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda-autoscaling-metrics-{{ include "gemma-7b.fullname" . }}
  labels:
    {{- include "gemma-7b.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - prometheuses
      - prometheuses/api
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keda-autoscaling-metrics-{{ include "gemma-7b.fullname" . }}
  labels:
    {{- include "gemma-7b.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-autoscaling-metrics-{{ include "gemma-7b.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: inference-prometheus-auth
    namespace: {{ .Release.Namespace }}
{{- end }}
